def store_win():
	import os
	def getdir(f_name):return os.path.join(os.path.dirname(__file__), f_name)
		# Garante que import de imagens funciona
	from PyQt5 import QtCore, QtGui, QtWidgets

	class Ui_store_window(object):
	    def setupUi(self, store_window):
	        store_window.setObjectName("store_window")
	        store_window.setFixedSize(997, 903) # Prende tamanho da janela
	        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
	        sizePolicy.setHorizontalStretch(0)
	        sizePolicy.setVerticalStretch(0)
	        sizePolicy.setHeightForWidth(store_window.sizePolicy().hasHeightForWidth())
	        store_window.setSizePolicy(sizePolicy)
	        icon = QtGui.QIcon()
	        icon.addPixmap(QtGui.QPixmap(getdir("icon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
	        store_window.setWindowIcon(icon)
	        self.centralwidget = QtWidgets.QWidget(store_window)
	        self.centralwidget.setObjectName("centralwidget")
	        self.label_2 = QtWidgets.QLabel(self.centralwidget)
	        self.label_2.setGeometry(QtCore.QRect(230, 40, 55, 16))
	        self.label_2.setText("")
	        self.label_2.setObjectName("label_2")
	        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
	        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 20, 941, 821))
	        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
	        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
	        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
	        self.verticalLayout_2.setObjectName("verticalLayout_2")
	        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
	        self.verticalLayout_3.setObjectName("verticalLayout_3")
	        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
	        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
	        self.img1 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
	        self.img1.setText("")
	        self.img1.setPixmap(QtGui.QPixmap(getdir("bird1.png")))
	        self.img1.setScaledContents(True)
	        self.img1.setObjectName("img1")
	        self.horizontalLayout_7.addWidget(self.img1)
	        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
	        self.horizontalLayout_7.addItem(spacerItem)
	        self.img2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
	        self.img2.setText("")
	        self.img2.setPixmap(QtGui.QPixmap(getdir("bird2.png")))
	        self.img2.setScaledContents(True)
	        self.img2.setObjectName("img2")
	        self.horizontalLayout_7.addWidget(self.img2)
	        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
	        self.horizontalLayout_7.addItem(spacerItem1)

	        self.img3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
	        self.img3.setText("")
	        self.img3.setPixmap(QtGui.QPixmap(getdir("bird3.png")))
	        self.img3.setScaledContents(True)
	        self.img3.setObjectName("img3")
	        self.horizontalLayout_7.addWidget(self.img3)
	        spacerItem2 = QtWidgets.QSpacerItem(40, 18, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
	        self.horizontalLayout_7.addItem(spacerItem2)

	        self.img4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
	        self.img4.setText("")
	        self.img4.setPixmap(QtGui.QPixmap(getdir("bird4.png")))
	        self.img4.setScaledContents(True)
	        self.img4.setObjectName("img4")
	        self.horizontalLayout_7.addWidget(self.img4)
	        spacerItem3 = QtWidgets.QSpacerItem(40, 18, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
	        self.horizontalLayout_7.addItem(spacerItem3)

	        self.img5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
	        self.img5.setText("")
	        self.img5.setPixmap(QtGui.QPixmap(getdir("bird5.png")))
	        self.img5.setScaledContents(True)
	        self.img5.setObjectName("img5")
	        self.horizontalLayout_7.addWidget(self.img5)
	        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
	        self.verticalLayout_2.addLayout(self.verticalLayout_3)
	        self.verticalLayout = QtWidgets.QVBoxLayout()
	        self.verticalLayout.setObjectName("verticalLayout")
	        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
	        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
	        self.buy1 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
	        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
	        sizePolicy.setHorizontalStretch(0)
	        sizePolicy.setVerticalStretch(0)
	        sizePolicy.setHeightForWidth(self.buy1.sizePolicy().hasHeightForWidth())
	        self.buy1.setSizePolicy(sizePolicy)
	        self.buy1.setMaximumSize(QtCore.QSize(250, 70))
	       
	        font = QtGui.QFont()
	        font.setFamily("Arial")
	        font.setPointSize(15)
	        font.setBold(True)
	        font.setWeight(75)
	        self.buy1.setFont(font)
	        self.buy1.setStyleSheet("background-color: rgb(255, 206, 26);")
	        self.buy1.setObjectName("buy1")
	        self.horizontalLayout_2.addWidget(self.buy1)
	        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
	        self.horizontalLayout_2.addItem(spacerItem4)
	        self.buy2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
	        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
	        sizePolicy.setHorizontalStretch(0)
	        sizePolicy.setVerticalStretch(0)
	        sizePolicy.setHeightForWidth(self.buy2.sizePolicy().hasHeightForWidth())
	        self.buy2.setSizePolicy(sizePolicy)
	        self.buy2.setMaximumSize(QtCore.QSize(250, 70))
	        
	        font = QtGui.QFont()
	        font.setFamily("Arial")
	        font.setPointSize(15)
	        font.setBold(True)
	        font.setWeight(75)
	        self.buy2.setFont(font)
	        self.buy2.setStyleSheet("background-color: rgb(255, 206, 26);")
	        self.buy2.setObjectName("buy2")
	        self.horizontalLayout_2.addWidget(self.buy2)
	        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
	        self.horizontalLayout_2.addItem(spacerItem5)
	        self.buy3 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
	        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
	        sizePolicy.setHorizontalStretch(0)
	        sizePolicy.setVerticalStretch(0)
	        sizePolicy.setHeightForWidth(self.buy3.sizePolicy().hasHeightForWidth())
	        self.buy3.setSizePolicy(sizePolicy)
	        self.buy3.setMaximumSize(QtCore.QSize(250, 70))

	        font = QtGui.QFont()
	        font.setFamily("Arial")
	        font.setPointSize(15)
	        font.setBold(True)
	        font.setWeight(75)
	        self.buy3.setFont(font)
	        self.buy3.setStyleSheet("background-color: rgb(255, 206, 26);")
	        self.buy3.setObjectName("buy3")
	        self.horizontalLayout_2.addWidget(self.buy3)
	        spacerItem6 = QtWidgets.QSpacerItem(40, 18, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
	        self.horizontalLayout_2.addItem(spacerItem6)
	        self.buy4 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
	        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
	        sizePolicy.setHorizontalStretch(0)
	        sizePolicy.setVerticalStretch(0)
	        sizePolicy.setHeightForWidth(self.buy4.sizePolicy().hasHeightForWidth())
	        self.buy4.setSizePolicy(sizePolicy)
	        self.buy4.setMaximumSize(QtCore.QSize(250, 70))

	        font = QtGui.QFont()
	        font.setFamily("Arial")
	        font.setPointSize(15)
	        font.setBold(True)
	        font.setWeight(75)
	        self.buy4.setFont(font)
	        self.buy4.setStyleSheet("background-color: rgb(255, 206, 26);")
	        self.buy4.setObjectName("buy4")
	        self.horizontalLayout_2.addWidget(self.buy4)
	        spacerItem7 = QtWidgets.QSpacerItem(40, 18, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
	        self.horizontalLayout_2.addItem(spacerItem7)
	        self.buy5 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
	        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
	        sizePolicy.setHorizontalStretch(0)
	        sizePolicy.setVerticalStretch(0)
	        sizePolicy.setHeightForWidth(self.buy5.sizePolicy().hasHeightForWidth())
	        self.buy5.setSizePolicy(sizePolicy)
	        self.buy5.setMaximumSize(QtCore.QSize(250, 70))
	    
	        font = QtGui.QFont()
	        font.setFamily("Arial")
	        font.setPointSize(15)
	        font.setBold(True)
	        font.setWeight(75)
	        self.buy5.setFont(font)
	        self.buy5.setStyleSheet("background-color: rgb(255, 206, 26);")
	        self.buy5.setObjectName("buy5")
	        self.horizontalLayout_2.addWidget(self.buy5)
	        self.verticalLayout.addLayout(self.horizontalLayout_2)
	        self.verticalLayout_2.addLayout(self.verticalLayout)
	        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
	        self.verticalLayout_2.addItem(spacerItem8)
	        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
	        self.verticalLayout_5.setObjectName("verticalLayout_5")
	        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
	        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
	        self.img6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
	        self.img6.setMaximumSize(QtCore.QSize(70, 150))
	        self.img6.setText("")
	        self.img6.setPixmap(QtGui.QPixmap(getdir("pipe1.png")))
	        self.img6.setScaledContents(True)
	        self.img6.setObjectName("img6")
	        self.horizontalLayout_9.addWidget(self.img6)
	        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
	        self.horizontalLayout_9.addItem(spacerItem9)
	        self.img7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
	        self.img7.setMaximumSize(QtCore.QSize(70, 150))
	        self.img7.setText("")
	        self.img7.setPixmap(QtGui.QPixmap(getdir("pipe2.png")))
	        self.img7.setScaledContents(True)
	        self.img7.setObjectName("img7")
	        self.horizontalLayout_9.addWidget(self.img7)
	        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
	        self.horizontalLayout_9.addItem(spacerItem10)
	        self.img8 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
	        self.img8.setMaximumSize(QtCore.QSize(70, 150))
	        self.img8.setText("")
	        self.img8.setPixmap(QtGui.QPixmap(getdir("pipe3.png")))
	        self.img8.setScaledContents(True)
	        self.img8.setObjectName("img8")
	        self.horizontalLayout_9.addWidget(self.img8)
	        spacerItem11 = QtWidgets.QSpacerItem(40, 18, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
	        self.horizontalLayout_9.addItem(spacerItem11)
	        self.img9 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
	        self.img9.setMaximumSize(QtCore.QSize(70, 150))
	        self.img9.setText("")
	        self.img9.setPixmap(QtGui.QPixmap(getdir("pipe4.png")))
	        self.img9.setScaledContents(True)
	        self.img9.setObjectName("img9")
	        self.horizontalLayout_9.addWidget(self.img9)
	        spacerItem12 = QtWidgets.QSpacerItem(40, 18, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
	        self.horizontalLayout_9.addItem(spacerItem12)
	        self.img10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
	        self.img10.setMaximumSize(QtCore.QSize(70, 150))
	        self.img10.setText("")
	        self.img10.setPixmap(QtGui.QPixmap(getdir("pipe5.png")))
	        self.img10.setScaledContents(True)
	        self.img10.setObjectName("img10")
	        self.horizontalLayout_9.addWidget(self.img10)
	        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
	        self.verticalLayout_2.addLayout(self.verticalLayout_5)
	        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
	        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
	        self.buy6 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
	        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
	        sizePolicy.setHorizontalStretch(0)
	        sizePolicy.setVerticalStretch(0)
	        sizePolicy.setHeightForWidth(self.buy6.sizePolicy().hasHeightForWidth())
	        self.buy6.setSizePolicy(sizePolicy)
	        self.buy6.setMaximumSize(QtCore.QSize(250, 70))
	  
	        font = QtGui.QFont()
	        font.setFamily("Arial")
	        font.setPointSize(15)
	        font.setBold(True)
	        font.setWeight(75)
	        self.buy6.setFont(font)
	        self.buy6.setStyleSheet("background-color: rgb(255, 206, 26);")
	        self.buy6.setObjectName("buy6")
	        self.horizontalLayout_4.addWidget(self.buy6)
	        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
	        self.horizontalLayout_4.addItem(spacerItem13)
	        self.buy7 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
	        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
	        sizePolicy.setHorizontalStretch(0)
	        sizePolicy.setVerticalStretch(0)
	        sizePolicy.setHeightForWidth(self.buy7.sizePolicy().hasHeightForWidth())
	        self.buy7.setSizePolicy(sizePolicy)
	        self.buy7.setMaximumSize(QtCore.QSize(250, 70))

	        font = QtGui.QFont()
	        font.setFamily("Arial")
	        font.setPointSize(15)
	        font.setBold(True)
	        font.setWeight(75)
	        self.buy7.setFont(font)
	        self.buy7.setStyleSheet("background-color: rgb(255, 206, 26);")
	        self.buy7.setObjectName("buy7")
	        self.horizontalLayout_4.addWidget(self.buy7)
	        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
	        self.horizontalLayout_4.addItem(spacerItem14)
	        self.buy8 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
	        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
	        sizePolicy.setHorizontalStretch(0)
	        sizePolicy.setVerticalStretch(0)
	        sizePolicy.setHeightForWidth(self.buy8.sizePolicy().hasHeightForWidth())
	        self.buy8.setSizePolicy(sizePolicy)
	        self.buy8.setMaximumSize(QtCore.QSize(250, 70))

	        font = QtGui.QFont()
	        font.setFamily("Arial")
	        font.setPointSize(15)
	        font.setBold(True)
	        font.setWeight(75)
	        self.buy8.setFont(font)
	        self.buy8.setStyleSheet("background-color: rgb(255, 206, 26);")
	        self.buy8.setObjectName("buy8")
	        self.horizontalLayout_4.addWidget(self.buy8)
	        spacerItem15 = QtWidgets.QSpacerItem(40, 18, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
	        self.horizontalLayout_4.addItem(spacerItem15)
	        self.buy9 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
	        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
	        sizePolicy.setHorizontalStretch(0)
	        sizePolicy.setVerticalStretch(0)
	        sizePolicy.setHeightForWidth(self.buy9.sizePolicy().hasHeightForWidth())
	        self.buy9.setSizePolicy(sizePolicy)
	        self.buy9.setMaximumSize(QtCore.QSize(250, 70))

	        font = QtGui.QFont()
	        font.setFamily("Arial")
	        font.setPointSize(15)
	        font.setBold(True)
	        font.setWeight(75)
	        self.buy9.setFont(font)
	        self.buy9.setStyleSheet("background-color: rgb(255, 206, 26);")
	        self.buy9.setObjectName("buy9")
	        self.horizontalLayout_4.addWidget(self.buy9)
	        spacerItem16 = QtWidgets.QSpacerItem(40, 18, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
	        self.horizontalLayout_4.addItem(spacerItem16)
	        self.buy10 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
	        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
	        sizePolicy.setHorizontalStretch(0)
	        sizePolicy.setVerticalStretch(0)
	        sizePolicy.setHeightForWidth(self.buy10.sizePolicy().hasHeightForWidth())
	        self.buy10.setSizePolicy(sizePolicy)
	        self.buy10.setMaximumSize(QtCore.QSize(250, 70))

	        font = QtGui.QFont()
	        font.setFamily("Arial")
	        font.setPointSize(15)
	        font.setBold(True)
	        font.setWeight(75)
	        self.buy10.setFont(font)
	        self.buy10.setStyleSheet("background-color: rgb(255, 206, 26);")
	        self.buy10.setObjectName("buy10")
	        self.horizontalLayout_4.addWidget(self.buy10)
	        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
	        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
	        self.verticalLayout_2.addItem(spacerItem17)
	        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
	        self.verticalLayout_6.setObjectName("verticalLayout_6")
	        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
	        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
	        self.img11 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
	        self.img11.setMaximumSize(QtCore.QSize(80, 150))
	        self.img11.setText("")
	        self.img11.setPixmap(QtGui.QPixmap(getdir("sky2.png")))
	        self.img11.setScaledContents(True)
	        self.img11.setObjectName("img11")
	        self.horizontalLayout_10.addWidget(self.img11)
	        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
	        self.horizontalLayout_10.addItem(spacerItem18)
	        self.img12 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
	        self.img12.setMaximumSize(QtCore.QSize(80, 150))
	        self.img12.setText("")
	        self.img12.setPixmap(QtGui.QPixmap(getdir("sky3.png")))
	        self.img12.setScaledContents(True)
	        self.img12.setObjectName("img12")
	        self.horizontalLayout_10.addWidget(self.img12)
	        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
	        self.horizontalLayout_10.addItem(spacerItem19)
	        self.img13 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
	        self.img13.setMaximumSize(QtCore.QSize(80, 150))
	        self.img13.setText("")
	        self.img13.setPixmap(QtGui.QPixmap(getdir("sky1.xpm")))
	        self.img13.setScaledContents(True)
	        self.img13.setObjectName("img13")
	        self.horizontalLayout_10.addWidget(self.img13)
	        spacerItem20 = QtWidgets.QSpacerItem(40, 18, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
	        self.horizontalLayout_10.addItem(spacerItem20)
	        self.img14 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
	        self.img14.setMaximumSize(QtCore.QSize(80, 150))
	        self.img14.setText("")
	        self.img14.setPixmap(QtGui.QPixmap(getdir("sky4.jpg")))
	        self.img14.setScaledContents(True)
	        self.img14.setObjectName("img14")
	        self.horizontalLayout_10.addWidget(self.img14)
	        spacerItem21 = QtWidgets.QSpacerItem(40, 18, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
	        self.horizontalLayout_10.addItem(spacerItem21)
	        self.img15 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
	        self.img15.setMaximumSize(QtCore.QSize(80, 150))
	        self.img15.setText("")
	        self.img15.setPixmap(QtGui.QPixmap(""))
	        self.img15.setScaledContents(True)
	        self.img15.setObjectName("img15")
	        self.horizontalLayout_10.addWidget(self.img15)
	        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
	        self.verticalLayout_2.addLayout(self.verticalLayout_6)
	        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
	        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
	        self.buy11 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
	        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
	        sizePolicy.setHorizontalStretch(0)
	        sizePolicy.setVerticalStretch(0)
	        sizePolicy.setHeightForWidth(self.buy11.sizePolicy().hasHeightForWidth())
	        self.buy11.setSizePolicy(sizePolicy)
	        self.buy11.setMaximumSize(QtCore.QSize(250, 70))

	        font = QtGui.QFont()
	        font.setFamily("Arial")
	        font.setPointSize(15)
	        font.setBold(True)
	        font.setWeight(75)
	        self.buy11.setFont(font)
	        self.buy11.setStyleSheet("background-color: rgb(255, 206, 26);")
	        self.buy11.setObjectName("buy11")
	        self.horizontalLayout_5.addWidget(self.buy11)
	        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
	        self.horizontalLayout_5.addItem(spacerItem22)
	        self.buy12 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
	        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
	        sizePolicy.setHorizontalStretch(0)
	        sizePolicy.setVerticalStretch(0)
	        sizePolicy.setHeightForWidth(self.buy12.sizePolicy().hasHeightForWidth())
	        self.buy12.setSizePolicy(sizePolicy)
	        self.buy12.setMaximumSize(QtCore.QSize(250, 70))
	        font = QtGui.QFont()
	        font.setFamily("Arial")
	        font.setPointSize(15)
	        font.setBold(True)
	        font.setWeight(75)
	        self.buy12.setFont(font)
	        self.buy12.setStyleSheet("background-color: rgb(255, 206, 26);")
	        self.buy12.setObjectName("buy12")
	        self.horizontalLayout_5.addWidget(self.buy12)
	        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
	        self.horizontalLayout_5.addItem(spacerItem23)
	        self.buy13 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
	        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
	        sizePolicy.setHorizontalStretch(0)
	        sizePolicy.setVerticalStretch(0)
	        sizePolicy.setHeightForWidth(self.buy13.sizePolicy().hasHeightForWidth())
	        self.buy13.setSizePolicy(sizePolicy)
	        self.buy13.setMaximumSize(QtCore.QSize(250, 70))
	        
	        font = QtGui.QFont()
	        font.setFamily("Arial")
	        font.setPointSize(15)
	        font.setBold(True)
	        font.setWeight(75)
	        self.buy13.setFont(font)
	        self.buy13.setStyleSheet("background-color: rgb(255, 206, 26);")
	        self.buy13.setObjectName("buy13")
	        self.horizontalLayout_5.addWidget(self.buy13)
	        spacerItem24 = QtWidgets.QSpacerItem(40, 18, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
	        self.horizontalLayout_5.addItem(spacerItem24)
	        self.buy14 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
	        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
	        sizePolicy.setHorizontalStretch(0)
	        sizePolicy.setVerticalStretch(0)
	        sizePolicy.setHeightForWidth(self.buy14.sizePolicy().hasHeightForWidth())
	        self.buy14.setSizePolicy(sizePolicy)
	        self.buy14.setMaximumSize(QtCore.QSize(250, 70))
	        
	        font = QtGui.QFont()
	        font.setFamily("Arial")
	        font.setPointSize(15)
	        font.setBold(True)
	        font.setWeight(75)
	        self.buy14.setFont(font)
	        self.buy14.setStyleSheet("background-color: rgb(255, 206, 26);")
	        self.buy14.setObjectName("buy14")
	        self.horizontalLayout_5.addWidget(self.buy14)
	        spacerItem25 = QtWidgets.QSpacerItem(40, 18, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
	        self.horizontalLayout_5.addItem(spacerItem25)
	        self.buy15 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
	        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
	        sizePolicy.setHorizontalStretch(0)
	        sizePolicy.setVerticalStretch(0)
	        sizePolicy.setHeightForWidth(self.buy15.sizePolicy().hasHeightForWidth())
	        self.buy15.setSizePolicy(sizePolicy)
	        self.buy15.setMaximumSize(QtCore.QSize(250, 70))
	        
	        font = QtGui.QFont()
	        font.setFamily("Arial")
	        font.setPointSize(15)
	        font.setBold(True)
	        font.setWeight(75)
	        self.buy15.setFont(font)
	        self.buy15.setStyleSheet("background-color: rgb(255, 160, 26);")
	        self.buy15.setObjectName("buy15")
	        self.horizontalLayout_5.addWidget(self.buy15)
	        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
	        self.label_31 = QtWidgets.QLabel(self.centralwidget)
	        self.label_31.setGeometry(QtCore.QRect(1010, 630, 55, 16))
	        self.label_31.setText("")
	        self.label_31.setObjectName("label_31")
	        self.label = QtWidgets.QLabel(self.centralwidget)
	        self.label.setGeometry(QtCore.QRect(0, -10, 1001, 921))
	        self.label.setText("")
	        self.label.setPixmap(QtGui.QPixmap(getdir("sky.png")))
	        self.label.setScaledContents(True)
	        self.label.setObjectName("label")
	        self.Back_Label = QtWidgets.QLabel(self.centralwidget)
	        self.Back_Label.setGeometry(QtCore.QRect(360, 840, 281, 51))
	        font = QtGui.QFont()
	        font.setPointSize(15)
	        font.setBold(False)
	        font.setWeight(50)
	        self.Back_Label.setFont(font)
	        self.Back_Label.setObjectName("Back_Label")
	        self.label.raise_()
	        self.label_2.raise_()
	        self.verticalLayoutWidget_2.raise_()
	        self.label_31.raise_()
	        self.Back_Label.raise_()
	        store_window.setCentralWidget(self.centralwidget)

	        self.retranslateUi(store_window)
	        QtCore.QMetaObject.connectSlotsByName(store_window)


	        #Button Function
	        self.buy1.clicked.connect(lambda: print("buy1"))
	        self.buy2.clicked.connect(lambda: print("buy2"))
	        self.buy3.clicked.connect(lambda: print("buy3"))
	        self.buy4.clicked.connect(lambda: print("buy4"))
	        self.buy5.clicked.connect(lambda: print("buy5"))
	        self.buy6.clicked.connect(lambda: print("buy6"))
	        self.buy7.clicked.connect(lambda: print("buy7"))
	        self.buy8.clicked.connect(lambda: print("buy8"))
	        self.buy9.clicked.connect(lambda: print("buy9"))
	        self.buy10.clicked.connect(lambda: print("buy10"))
	        self.buy11.clicked.connect(lambda: print("buy11"))
	        self.buy12.clicked.connect(lambda: print("buy12")) 	
	        self.buy13.clicked.connect(lambda: print("buy13"))
	        self.buy14.clicked.connect(lambda: print("buy14"))
	        self.buy15.clicked.connect(lambda: print("Back")) 	
			


	    def retranslateUi(self, store_window):
	        _translate = QtCore.QCoreApplication.translate
	        store_window.setWindowTitle(_translate("store_window", "Flappy Bird - Store"))
	        self.buy1.setText(_translate("store_window", "10 $ "))
	        self.buy2.setText(_translate("store_window", "10 $ "))
	        self.buy3.setText(_translate("store_window", "10 $ "))
	        self.buy4.setText(_translate("store_window", "50 $ "))
	        self.buy5.setText(_translate("store_window", "100 $ "))
	        self.buy6.setText(_translate("store_window", "15 $ "))
	        self.buy7.setText(_translate("store_window", "15 $ "))
	        self.buy8.setText(_translate("store_window", "15 $ "))
	        self.buy9.setText(_translate("store_window", "15 $ "))
	        self.buy10.setText(_translate("store_window", "15 $ "))
	        self.buy11.setText(_translate("store_window", " 40 $ "))
	        self.buy12.setText(_translate("store_window", " 40 $ "))
	        self.buy13.setText(_translate("store_window", " 40 $ "))
	        self.buy14.setText(_translate("store_window", " 40 $ "))
	        self.buy15.setText(_translate("store_window", " Back "))
	
	import sys
	app = QtWidgets.QApplication(sys.argv)
	store_window = QtWidgets.QMainWindow()
	ui = Ui_store_window()
	ui.setupUi(store_window)
	store_window.show()
	sys.exit(app.exec_())

store_win()